Step1: Load dataset

In [131]:
import pandas as pd
df = pd.read_csv("Combined_dataset.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

Step2: Explore data

In [132]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [133]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [134]:
df.shape

(1000, 24)

In [135]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [136]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

Step3: Handling missing values

In [138]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [139]:
#Filling missing discount values with 0, as it indicates no discount
df["discount"] = df["discount"].fillna(0)

#Filling missing values in other columns with appropriate messages
df["what_customers_said"] = df["what_customers_said"].fillna("Not Available")
df["seller_name"] = df["seller_name"].fillna("Unknown Seller")
df["seller_information"] = df["seller_information"].fillna("Not Available")
df["videos"] = df["videos"].fillna("No Video Available")
df["variations"] = df["variations"].fillna("No Variations Available")

In [140]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [141]:
#Observed that even after filling missing values, whole variations column actually empty.
df["variations"].value_counts()

variations
No Variations Available                                                                                                                                                562
[{}]                                                                                                                                                                   126
[{},{}]                                                                                                                                                                 85
[{},{},{}]                                                                                                                                                              52
[{},{},{},{}]                                                                                                                                                           34
[{},{},{},{},{}]                                                                                                                                                        33
[{},{},{},{},{},{}]                                                                                                                                                     25
[{},{},{},{},{},{},{},{}]                                                                                                                                               17
[{},{},{},{},{},{},{}]                                                                                                                                                  11
[{},{},{},{},{},{},{},{},{}]                                                                                                                                            10
[{},{},{},{},{},{},{},{},{},{},{}]                                                                                                                                       9
[{},{},{},{},{},{},{},{},{},{},{},{},{}]                                                                                                                                 8
[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]                                                                                                                              6
[{},{},{},{},{},{},{},{},{},{}]                                                                                                                                          6
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]                                                                                                                           5
[{},{},{},{},{},{},{},{},{},{},{},{}]                                                                                                                                    3
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]                                                                                                      2
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]                                                                                             1
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]                                                                                          1
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]                                                                                                                  1
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]                                                                                    1
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]      1
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]                                                                                                                        1
Name: count, dtype: int64

In [142]:
#As variations column is actually empty, replacing all values with "No Variations"
df["variations"] = "No Variations"

In [143]:
df["variations"].value_counts().head()

variations
No Variations    1000
Name: count, dtype: int64

In [144]:
#Observed that best_offer also have many empty dictionary values.
df["best_offer"].value_counts().head()

best_offer
{}                                                                                                                                                                                  306
{"applicable_on":"Orders above Rs. 649 (only on first purchase)","best_price":"414","coupon_code":"MYNTRA200","coupon_discount":" Rs. 185.0 off (check cart for final savings)"}     13
{"applicable_on":"Orders above Rs. 999 (only on first purchase)","best_price":"629","coupon_code":"MYNTRA300","coupon_discount":" Rs. 270.0 off (check cart for final savings)"}     10
{"applicable_on":"Orders above Rs. 999 (only on first purchase)","best_price":"559","coupon_code":"MYNTRA300","coupon_discount":" Rs. 240.0 off (check cart for final savings)"}      9
{"applicable_on":"Orders above Rs. 999 (only on first purchase)","best_price":"489","coupon_code":"MYNTRA300","coupon_discount":" Rs. 210.0 off (check cart for final savings)"}      9
Name: count, dtype: int64

In [145]:
#As best_offer column have many empty dictionary values, replacing all values with "No Offer"
df["best_offer"] = df["best_offer"].replace("{}", "No Offer")

In [146]:
df["best_offer"].value_counts().head()

best_offer
No Offer                                                                                                                                                                            306
{"applicable_on":"Orders above Rs. 649 (only on first purchase)","best_price":"414","coupon_code":"MYNTRA200","coupon_discount":" Rs. 185.0 off (check cart for final savings)"}     13
{"applicable_on":"Orders above Rs. 999 (only on first purchase)","best_price":"629","coupon_code":"MYNTRA300","coupon_discount":" Rs. 270.0 off (check cart for final savings)"}     10
{"applicable_on":"Orders above Rs. 999 (only on first purchase)","best_price":"559","coupon_code":"MYNTRA300","coupon_discount":" Rs. 240.0 off (check cart for final savings)"}      9
{"applicable_on":"Orders above Rs. 999 (only on first purchase)","best_price":"489","coupon_code":"MYNTRA300","coupon_discount":" Rs. 210.0 off (check cart for final savings)"}      9
Name: count, dtype: int64

Step4: Basic operations (filter rows, select columns)

In [147]:
#Filtering products with rating greater than 4
high_rated = df[df["rating"] > 4]
high_rated[["title", "rating"]].head()

            title  rating
1  Tommy Hilfiger     4.5
2           Lavie     4.4
3          F Gear     4.4
4       MYTRIDENT     4.7
5             H&M     4.5

In [148]:
#Filtering products with discount greater than 50%
high_discount = df[df["discount"] > 50]
high_discount[["title", "discount"]].head()

         title  discount
0  Lino Perros      58.0
2        Lavie      65.0
3       F Gear      52.0
6   AVI Living      65.0
7      My Room      54.0

In [149]:
#Showing only selected columns: title, rating, initial_price, final_price
selected_columns = df[["title", "rating", "initial_price", "final_price"]]
selected_columns.head()

            title  rating  initial_price  final_price
0     Lino Perros     3.8           3995  "₹3,995.00"
1  Tommy Hilfiger     4.5           2899  "₹2,899.00"
2           Lavie     4.4           2999  "₹2,999.00"
3          F Gear     4.4           1675  "₹1,675.00"
4       MYTRIDENT     4.7           2899  "₹2,899.00"

Step5: Checking Duplicate values

In [150]:
#Checking for duplicate entries in the dataset
df.duplicated().sum()
#There are no duplicate entries in the dataset.

np.int64(0)

Step6: Creating new usefull columns

In [151]:
#Creating a new column "amount_saved" to calculate the amount saved by customers based on initial price and discount percentage
df["amount_saved"] = (df["initial_price"] * df["discount"]) / 100

In [152]:
#Creating a new column "top_product" to identify products which are highly rated and have good number of ratings.
df["top_product"] = (
    (df["ratings_count"] > 100) &
    (df["rating"] > 3.5)
)

In [153]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,amount_saved,top_product
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Not Available,No Variations,No Offer,"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2317.10,False
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,No Variations,No Offer,"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1014.65,False
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,No Variations,No Offer,"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1949.35,True
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,No Variations,No Offer,"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,871.00,True
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video Available,Not Available,No Variations,No Offer,"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,492.83,False

Step7: Extracting new csv file

In [154]:
df.to_csv("cleaned_shopping_dataset.csv", index=False)